/*
 * This file is generated by jOOQ.
 */
package com.fooddiary.api.jooq;


import com.fooddiary.api.jooq.tables.Diarybook;
import com.fooddiary.api.jooq.tables.Memo;
import com.fooddiary.api.jooq.tables.Photo;
import com.fooddiary.api.jooq.tables.Policy;
import com.fooddiary.api.jooq.tables.Session;
import com.fooddiary.api.jooq.tables.Tag;
import com.fooddiary.api.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyFoodDiarybook extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>my_food_diarybook</code>
     */
    public static final MyFoodDiarybook MY_FOOD_DIARYBOOK = new MyFoodDiarybook();

    /**
     * The table <code>my_food_diarybook.diarybook</code>.
     */
    public final Diarybook DIARYBOOK = Diarybook.DIARYBOOK;

    /**
     * The table <code>my_food_diarybook.memo</code>.
     */
    public final Memo MEMO = Memo.MEMO;

    /**
     * The table <code>my_food_diarybook.photo</code>.
     */
    public final Photo PHOTO = Photo.PHOTO;

    /**
     * 정책테이블
     */
    public final Policy POLICY = Policy.POLICY;

    /**
     * The table <code>my_food_diarybook.session</code>.
     */
    public final Session SESSION = Session.SESSION;

    /**
     * The table <code>my_food_diarybook.tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * The table <code>my_food_diarybook.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private MyFoodDiarybook() {
        super("my_food_diarybook", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Diarybook.DIARYBOOK,
            Memo.MEMO,
            Photo.PHOTO,
            Policy.POLICY,
            Session.SESSION,
            Tag.TAG,
            User.USER
        );
    }
}
