/*
 * This file is generated by jOOQ.
 */
package com.fooddiary.api.jooq;


import com.fooddiary.api.jooq.tables.Diarybook;
import com.fooddiary.api.jooq.tables.Memo;
import com.fooddiary.api.jooq.tables.Photo;
import com.fooddiary.api.jooq.tables.Policy;
import com.fooddiary.api.jooq.tables.Session;
import com.fooddiary.api.jooq.tables.Tag;
import com.fooddiary.api.jooq.tables.User;


/**
 * Convenience access to all tables in my_food_diarybook.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>my_food_diarybook.diarybook</code>.
     */
    public static final Diarybook DIARYBOOK = Diarybook.DIARYBOOK;

    /**
     * The table <code>my_food_diarybook.memo</code>.
     */
    public static final Memo MEMO = Memo.MEMO;

    /**
     * The table <code>my_food_diarybook.photo</code>.
     */
    public static final Photo PHOTO = Photo.PHOTO;

    /**
     * 정책테이블
     */
    public static final Policy POLICY = Policy.POLICY;

    /**
     * The table <code>my_food_diarybook.session</code>.
     */
    public static final Session SESSION = Session.SESSION;

    /**
     * The table <code>my_food_diarybook.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>my_food_diarybook.user</code>.
     */
    public static final User USER = User.USER;
}
