spring:
  datasource:
    url: jdbc:mysql://my-food-diarybook.cuvruxzyxphr.ap-northeast-2.rds.amazonaws.com/my_food_diarybook
    username: my_food_diary
    password: myfooddiary2
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 3
      connection-timeout: 10000
      connection-test-sql: select 1

  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: false

cloud:
  aws:
    s3:
      dir: production