spring:
  datasource:
    url: jdbc:mysql://localhost/my_food_diarybook
    username: root
    password: 1212
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 3
      connection-timeout: 10000
      connection-test-sql: select 1

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true