# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# default profile
spring:
  profiles:
    active: local
  # exclude logging
#  security:
#    user:
#      password: @YOUR_PASSWORD@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 35MB
server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100 
    connection-timeout: 10000 # 10초 대기 스레드는 타임아웃
  port: 8080
#
#cloud:
#  aws:
#    credentials:
#      accessKey: @YOUR_ACCESS_KEY@
#      secretKey: @YOUR_SECRET_KEY@
#    s3:
#      bucket: @YOUR_BUCKET@
#    region:
#      static: @YOUR_REGION@
#    stack:
#      auto: false

food-diary:
  pw-try-limit: 5
  pw-reset-size: 8