/*
 * This file is generated by jOOQ.
 */
package com.fooddiary.api.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UserCreatePath implements EnumType {

    google("google"),

    kakao("kakao"),

    none("none");

    private final String literal;

    private UserCreatePath(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static UserCreatePath lookupLiteral(String literal) {
        return EnumType.lookupLiteral(UserCreatePath.class, literal);
    }
}
