/*
 * This file is generated by jOOQ.
 */
package com.fooddiary.api.jooq.tables.pojos;


import com.fooddiary.api.jooq.enums.DiarybookMealType;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Diarybook implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private LocalDate date;
    private LocalDateTime createAt;
    private Integer createUserId;
    private DiarybookMealType mealType;

    public Diarybook() {}

    public Diarybook(Diarybook value) {
        this.id = value.id;
        this.date = value.date;
        this.createAt = value.createAt;
        this.createUserId = value.createUserId;
        this.mealType = value.mealType;
    }

    public Diarybook(
        Long id,
        LocalDate date,
        LocalDateTime createAt,
        Integer createUserId,
        DiarybookMealType mealType
    ) {
        this.id = id;
        this.date = date;
        this.createAt = createAt;
        this.createUserId = createUserId;
        this.mealType = mealType;
    }

    /**
     * Getter for <code>my_food_diarybook.diarybook.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>my_food_diarybook.diarybook.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>my_food_diarybook.diarybook.date</code>.
     */
    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Setter for <code>my_food_diarybook.diarybook.date</code>.
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * Getter for <code>my_food_diarybook.diarybook.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>my_food_diarybook.diarybook.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * Getter for <code>my_food_diarybook.diarybook.create_user_id</code>.
     */
    public Integer getCreateUserId() {
        return this.createUserId;
    }

    /**
     * Setter for <code>my_food_diarybook.diarybook.create_user_id</code>.
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * Getter for <code>my_food_diarybook.diarybook.meal_type</code>.
     */
    public DiarybookMealType getMealType() {
        return this.mealType;
    }

    /**
     * Setter for <code>my_food_diarybook.diarybook.meal_type</code>.
     */
    public void setMealType(DiarybookMealType mealType) {
        this.mealType = mealType;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Diarybook other = (Diarybook) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        if (this.createUserId == null) {
            if (other.createUserId != null)
                return false;
        }
        else if (!this.createUserId.equals(other.createUserId))
            return false;
        if (this.mealType == null) {
            if (other.mealType != null)
                return false;
        }
        else if (!this.mealType.equals(other.mealType))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        result = prime * result + ((this.createUserId == null) ? 0 : this.createUserId.hashCode());
        result = prime * result + ((this.mealType == null) ? 0 : this.mealType.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Diarybook (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(createAt);
        sb.append(", ").append(createUserId);
        sb.append(", ").append(mealType);

        sb.append(")");
        return sb.toString();
    }
}
