/*
 * This file is generated by jOOQ.
 */
package com.fooddiary.api.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Memo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String memo;
    private LocalDateTime createAt;
    private Long diarybookId;

    public Memo() {}

    public Memo(Memo value) {
        this.id = value.id;
        this.memo = value.memo;
        this.createAt = value.createAt;
        this.diarybookId = value.diarybookId;
    }

    public Memo(
        Long id,
        String memo,
        LocalDateTime createAt,
        Long diarybookId
    ) {
        this.id = id;
        this.memo = memo;
        this.createAt = createAt;
        this.diarybookId = diarybookId;
    }

    /**
     * Getter for <code>my_food_diarybook.memo.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>my_food_diarybook.memo.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>my_food_diarybook.memo.memo</code>.
     */
    public String getMemo() {
        return this.memo;
    }

    /**
     * Setter for <code>my_food_diarybook.memo.memo</code>.
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * Getter for <code>my_food_diarybook.memo.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>my_food_diarybook.memo.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * Getter for <code>my_food_diarybook.memo.diarybook_id</code>.
     */
    public Long getDiarybookId() {
        return this.diarybookId;
    }

    /**
     * Setter for <code>my_food_diarybook.memo.diarybook_id</code>.
     */
    public void setDiarybookId(Long diarybookId) {
        this.diarybookId = diarybookId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Memo other = (Memo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.memo == null) {
            if (other.memo != null)
                return false;
        }
        else if (!this.memo.equals(other.memo))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        if (this.diarybookId == null) {
            if (other.diarybookId != null)
                return false;
        }
        else if (!this.diarybookId.equals(other.diarybookId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.memo == null) ? 0 : this.memo.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        result = prime * result + ((this.diarybookId == null) ? 0 : this.diarybookId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Memo (");

        sb.append(id);
        sb.append(", ").append(memo);
        sb.append(", ").append(createAt);
        sb.append(", ").append(diarybookId);

        sb.append(")");
        return sb.toString();
    }
}
