/*
 * This file is generated by jOOQ.
 */
package com.fooddiary.api.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Photo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String realName;
    private String s3Key;
    private LocalDateTime createAt;
    private Long diarybookId;

    public Photo() {}

    public Photo(Photo value) {
        this.id = value.id;
        this.realName = value.realName;
        this.s3Key = value.s3Key;
        this.createAt = value.createAt;
        this.diarybookId = value.diarybookId;
    }

    public Photo(
        Long id,
        String realName,
        String s3Key,
        LocalDateTime createAt,
        Long diarybookId
    ) {
        this.id = id;
        this.realName = realName;
        this.s3Key = s3Key;
        this.createAt = createAt;
        this.diarybookId = diarybookId;
    }

    /**
     * Getter for <code>my_food_diarybook.photo.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>my_food_diarybook.photo.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>my_food_diarybook.photo.real_name</code>.
     */
    public String getRealName() {
        return this.realName;
    }

    /**
     * Setter for <code>my_food_diarybook.photo.real_name</code>.
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * Getter for <code>my_food_diarybook.photo.s3_key</code>.
     */
    public String getS3Key() {
        return this.s3Key;
    }

    /**
     * Setter for <code>my_food_diarybook.photo.s3_key</code>.
     */
    public void setS3Key(String s3Key) {
        this.s3Key = s3Key;
    }

    /**
     * Getter for <code>my_food_diarybook.photo.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>my_food_diarybook.photo.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * Getter for <code>my_food_diarybook.photo.diarybook_id</code>.
     */
    public Long getDiarybookId() {
        return this.diarybookId;
    }

    /**
     * Setter for <code>my_food_diarybook.photo.diarybook_id</code>.
     */
    public void setDiarybookId(Long diarybookId) {
        this.diarybookId = diarybookId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Photo other = (Photo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.realName == null) {
            if (other.realName != null)
                return false;
        }
        else if (!this.realName.equals(other.realName))
            return false;
        if (this.s3Key == null) {
            if (other.s3Key != null)
                return false;
        }
        else if (!this.s3Key.equals(other.s3Key))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        if (this.diarybookId == null) {
            if (other.diarybookId != null)
                return false;
        }
        else if (!this.diarybookId.equals(other.diarybookId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.realName == null) ? 0 : this.realName.hashCode());
        result = prime * result + ((this.s3Key == null) ? 0 : this.s3Key.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        result = prime * result + ((this.diarybookId == null) ? 0 : this.diarybookId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Photo (");

        sb.append(id);
        sb.append(", ").append(realName);
        sb.append(", ").append(s3Key);
        sb.append(", ").append(createAt);
        sb.append(", ").append(diarybookId);

        sb.append(")");
        return sb.toString();
    }
}
