/*
 * This file is generated by jOOQ.
 */
package com.fooddiary.api.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 정책테이블
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Policy implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String key;
    private String value;
    private LocalDateTime createAt;
    private LocalDateTime updateAt;

    public Policy() {}

    public Policy(Policy value) {
        this.id = value.id;
        this.key = value.key;
        this.value = value.value;
        this.createAt = value.createAt;
        this.updateAt = value.updateAt;
    }

    public Policy(
        Integer id,
        String key,
        String value,
        LocalDateTime createAt,
        LocalDateTime updateAt
    ) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.createAt = createAt;
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>my_food_diarybook.policy.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>my_food_diarybook.policy.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>my_food_diarybook.policy.key</code>.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>my_food_diarybook.policy.key</code>.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>my_food_diarybook.policy.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>my_food_diarybook.policy.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for <code>my_food_diarybook.policy.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>my_food_diarybook.policy.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * Getter for <code>my_food_diarybook.policy.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>my_food_diarybook.policy.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Policy other = (Policy) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.key == null) {
            if (other.key != null)
                return false;
        }
        else if (!this.key.equals(other.key))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        if (this.updateAt == null) {
            if (other.updateAt != null)
                return false;
        }
        else if (!this.updateAt.equals(other.updateAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        result = prime * result + ((this.updateAt == null) ? 0 : this.updateAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Policy (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(createAt);
        sb.append(", ").append(updateAt);

        sb.append(")");
        return sb.toString();
    }
}
