/*
 * This file is generated by jOOQ.
 */
package com.fooddiary.api.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tag implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long diarybookId;
    private String name;
    private LocalDateTime createAt;

    public Tag() {}

    public Tag(Tag value) {
        this.diarybookId = value.diarybookId;
        this.name = value.name;
        this.createAt = value.createAt;
    }

    public Tag(
        Long diarybookId,
        String name,
        LocalDateTime createAt
    ) {
        this.diarybookId = diarybookId;
        this.name = name;
        this.createAt = createAt;
    }

    /**
     * Getter for <code>my_food_diarybook.tag.diarybook_id</code>.
     */
    public Long getDiarybookId() {
        return this.diarybookId;
    }

    /**
     * Setter for <code>my_food_diarybook.tag.diarybook_id</code>.
     */
    public void setDiarybookId(Long diarybookId) {
        this.diarybookId = diarybookId;
    }

    /**
     * Getter for <code>my_food_diarybook.tag.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>my_food_diarybook.tag.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>my_food_diarybook.tag.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    /**
     * Setter for <code>my_food_diarybook.tag.create_at</code>.
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Tag other = (Tag) obj;
        if (this.diarybookId == null) {
            if (other.diarybookId != null)
                return false;
        }
        else if (!this.diarybookId.equals(other.diarybookId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.createAt == null) {
            if (other.createAt != null)
                return false;
        }
        else if (!this.createAt.equals(other.createAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.diarybookId == null) ? 0 : this.diarybookId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.createAt == null) ? 0 : this.createAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tag (");

        sb.append(diarybookId);
        sb.append(", ").append(name);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
